---
- hosts: OBBservers
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Transfer packages to remote location
      copy:
         src: '{{ item.src }}'
         dest: '{{ item.dest }}'
         owner: ansible
         group: ansible
         mode: 0775
      with_items:
         - { src: '/home/ansible/SensorLinuxInstaller-ASPIRE', dest: '/home/ansible/' }
         - { src: '/home/ansible/SensorLinuxInstaller-ASPIRE.cfg', dest: '/home/ansible/' }
    - name: Execute the script
      shell:
        cmd: ./SensorLinuxInstaller-ASPIRE -c SensorLinuxInstaller-ASPIRE.cfg -k D359549804C427FB58A1 -d false -l install.txt
    - name: Restart traps_pmd.service
      systemd:
        name: esensor.service
        state: restarted
